name: Update Domain List

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-list:
    runs-on: ubuntu-latest
    
    env:
      DOMAIN_URL: "https://trustpositif.kominfo.go.id/assets/db/domains"
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Fetch domains
        run: |
          now=$(date +"%Y-%m-%d_%H-%M-%S")
          echo "Fetching domains at $now"
          echo "URL: $DOMAIN_URL"
          
          # Fetch domains with better options
          curl --insecure \
               --connect-timeout 10 \
               --max-time 60 \
               --retry 3 \
               --retry-delay 5 \
               --retry-max-time 60 \
               -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0" \
               -H "Accept: text/plain,text/html,*/*" \
               -o blocked_domains.txt \
               -L \
               "$DOMAIN_URL"
          
          if [ -s blocked_domains.txt ]; then
            echo "Download successful"
            echo "Sample of first 5 domains:"
            head -n 5 blocked_domains.txt
          else
            echo "Failed to download domains"
            exit 1
          fi
      
      - name: Create artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: blocked-domains
          path: blocked_domains.txt
          retention-days: 1
      
      - name: Configure Git
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      
      - name: Commit and push if changed
        if: success()
        run: |
          if git diff --quiet blocked_domains.txt; then
            echo "No changes to commit"
          else
            git add blocked_domains.txt
            git commit -m "Update blocked domains [skip ci]"
            git push
          fi
